#!/usr/bin/env bash
set -euo pipefail

# Generate a TypeScript client for ds's OpenAPI.
# Requires either:
#  - npx openapi-typescript
#  - or openapi-generator-cli (npm pkg or Docker)

OUT_DIR=${1:-examples/dashboard/generated/ds-client}
SPEC=${2:-internal/server/openapi.yaml}

mkdir -p "$OUT_DIR"

if command -v npx >/dev/null 2>&1; then
  echo "Using openapi-typescript via npx…"
  npx openapi-typescript "$SPEC" --output "$OUT_DIR/types.ts"
  cat >"$OUT_DIR/README.md" <<EOF
This folder contains types generated by openapi-typescript from $SPEC.

Regenerate with:

  ../../scripts/generate-openapi-client.sh "$OUT_DIR" "$SPEC"
EOF
  echo "✓ Generated types at $OUT_DIR/types.ts"
  exit 0
fi

if command -v openapi-generator-cli >/dev/null 2>&1; then
  echo "Using openapi-generator-cli…"
  openapi-generator-cli generate -i "$SPEC" -g typescript-axios -o "$OUT_DIR"
  echo "✓ Generated client at $OUT_DIR"
  exit 0
fi

echo "No generator available. Install one of:\n  npm i -D openapi-typescript\n  npm i -g @openapitools/openapi-generator-cli"
exit 1

